GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Seo Dalmi",
    "username": "dalmi",
    "email": "dalmi@gmail.com",
    "password": "123456"
}

###
PUT http://localhost:3000/api/users/7d9ee7fe-5d23-4453-80ae-6ff4c06d612c
Content-Type: application/json

{
    "password": "654321"
}